version: '3.1'

services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - 3306:3306
    networks:
      - stock-quote-manager-network

  stock-manager:
    image: lucasvilela/stock-manager
    ports:
      - 8080:8080
    depends_on:
      - docker-mysql
    networks:
      - stock-quote-manager-network

  stock-quote-manager:
    build:
      dockerfile: Dockerfile
      context: .
    image: stock-quote-manager:1.0
    ports:
      - 8081:8081
    depends_on:
      - docker-mysql
    networks:
      - stock-quote-manager-network

networks:
  stock-quote-manager-network:
    driver: bridge